server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  name: "web"

  mail:
    host: smtp.gmail.com
    port: 587
    username: khoihv1@gmail.com
    password: hlnlxjtmaoyizyea  # Mật khẩu ứng dụng (App Password)
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    url: jdbc:mysql://localhost:3307/bhd_star?useSSL=false&serverTimezone=UTC
    username: root
    password: 100504
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  signerKey: "d+cNWwyPpTw3HwhOJWXtJ8ZbiVUTFdwfGdVXigHmMbafFr83Gm43VFBnMZIH0OU0"
  valid-duration: 3600  # in second
  refreshable-duration: 3600000


